/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package careerconnect;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        
        // Set Size,Location of JFlame.
        
        setSize(540, 760);
        setLocation(200, 100);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtusern = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtnumber = new javax.swing.JTextField();
        txtpass1 = new javax.swing.JPasswordField();
        combo = new javax.swing.JComboBox<>();
        BackLogin = new javax.swing.JButton();
        Register = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtpass2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(41, 99, 70,90));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255,90));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SIGN UP");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("First name");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Last Name");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gender");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Email");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Phone number");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Password");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("User Name");

        txtfname.setBackground(new java.awt.Color(255, 255, 255));
        txtfname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtfname.setForeground(new java.awt.Color(0, 0, 0));

        txtlname.setBackground(new java.awt.Color(255, 255, 255));
        txtlname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtlname.setForeground(new java.awt.Color(0, 0, 0));
        txtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnameActionPerformed(evt);
            }
        });

        txtusern.setBackground(new java.awt.Color(255, 255, 255));
        txtusern.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtusern.setForeground(new java.awt.Color(0, 0, 0));

        txtemail.setBackground(new java.awt.Color(255, 255, 255));
        txtemail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtemail.setForeground(new java.awt.Color(0, 0, 0));

        txtnumber.setBackground(new java.awt.Color(255, 255, 255));
        txtnumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnumber.setForeground(new java.awt.Color(0, 0, 0));
        txtnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumberKeyTyped(evt);
            }
        });

        txtpass1.setBackground(new java.awt.Color(255, 255, 255));
        txtpass1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpass1.setForeground(new java.awt.Color(0, 0, 0));
        txtpass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpass1ActionPerformed(evt);
            }
        });

        combo.setBackground(new java.awt.Color(255, 255, 255));
        combo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo.setForeground(new java.awt.Color(0, 0, 0));
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None ", "Male", "Female", "Others" }));

        BackLogin.setBackground(new java.awt.Color(0, 102, 102));
        BackLogin.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BackLogin.setForeground(new java.awt.Color(255, 255, 255));
        BackLogin.setText("Back to Login");
        BackLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackLoginActionPerformed(evt);
            }
        });

        Register.setBackground(new java.awt.Color(8, 105, 64));
        Register.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Register.setForeground(new java.awt.Color(255, 255, 255));
        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Confirm Pass");

        txtpass2.setBackground(new java.awt.Color(255, 255, 255));
        txtpass2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpass2.setForeground(new java.awt.Color(0, 0, 0));
        txtpass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpass2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7)
                        .addGap(34, 34, 34)
                        .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8)
                        .addGap(33, 33, 33)
                        .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel14)
                        .addGap(31, 31, 31)
                        .addComponent(txtusern, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel9)
                        .addGap(56, 56, 56)
                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel10)
                        .addGap(70, 70, 70)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel11)
                        .addGap(6, 6, 6)
                        .addComponent(txtnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtpass2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(41, 41, 41)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(BackLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtpass1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(122, 122, 122))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel7))
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel8))
                    .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel14))
                    .addComponent(txtusern, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9))
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel10))
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel11))
                    .addComponent(txtnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel12))
                    .addComponent(txtpass1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpass2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Register, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(BackLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(50, 100, 447, 600);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\career 12.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, -190, 600, 1030);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
       
       // Get input values from text fields
       
       String fname = txtfname.getText();
       String lname = txtlname.getText();
       String username = txtusern.getText();
       String gender = combo.getSelectedItem().toString();
       String email = txtemail.getText();
       String number = txtnumber.getText();
       String pass1 = String.valueOf(txtpass1.getText());
       String pass2 = String.valueOf(txtpass2.getText());
       
       //Check if all input fields are valid using the VerifyFields method
        if (VerifyFields()) {
            // Check if the username is unique using the CheckUsername method
            if (!CheckUsername(username)) {
            // Prepare the SQL query to insert user data into the 'applicants' table    
                PreparedStatement pst = null;
                String registerUserQuery = "INSERT INTO `applicants`(`Firstname`, `Lastname`, `Username`, `Gender`, `Email`, `Tel Phone`, `Password`) VALUES (?,?,?,?,?,?,?)";
                
                try {
                    // Create a connection to the database
                    Connection dbcon = DBConnection.DBConnection();
                    // Prepare the SQL statement
                    pst = (PreparedStatement)dbcon.prepareStatement(registerUserQuery);
                    pst.setString(1, fname);
                    pst.setString(2, lname);
                    pst.setString(3, username);
                    pst.setString(4, gender);
                    pst.setString(5, email);
                    pst.setString(6, number);
                    pst.setString(7, pass1);
                    
                    //Set Fields Empty.
                    txtfname.setText("");
                    txtlname.setText("");
                    txtemail.setText("");
                    txtnumber.setText("");
                    txtpass1.setText("");
                    txtpass2.setText("");
                    txtusern.setText("");
                    
                    // Run the update query and verify that it completed successfully.
                    if (pst.executeUpdate()!=0) {
                       JOptionPane.showMessageDialog(null, "Your Account Has Been Created.");
                       SignIn s = new SignIn();
                       s.setTitle("SignIn");
                       s.setVisible(true);
                     // Display an error message if the update query fails   
                    }else{
                    JOptionPane.showMessageDialog(rootPane, "Check Your Information.","ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
      
        
    }//GEN-LAST:event_RegisterActionPerformed

    private void txtpass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpass1ActionPerformed

    private void txtnumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumberKeyTyped

        // Make Phone number TextField Allow only numbers
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtnumberKeyTyped

    private void txtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlnameActionPerformed

    private void txtpass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpass2ActionPerformed

    private void BackLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackLoginActionPerformed
        dispose();
        SignIn s = new SignIn();
        s.setVisible(true);
    }//GEN-LAST:event_BackLoginActionPerformed
    public  boolean VerifyFields(){
        
        //Check if Our Fields are Empty.
        String fname = txtfname.getText();
        String lname = txtlname.getText();
        String username = txtusern.getText();
        String gender = combo.getSelectedItem().toString();
        String email = txtemail.getText();
        String number = txtnumber.getText();
        String pass1 = String.valueOf(txtpass1.getText());
        String pass2 = String.valueOf(txtpass2.getText());
        if (fname.isEmpty()|| lname.isEmpty()|| username.isEmpty()|| gender.isEmpty()|| email.isEmpty()
            || number.isEmpty()|| pass1.isEmpty()|| pass2.trim().isEmpty()){
            
            JOptionPane.showMessageDialog(rootPane, "Check Your Fields.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
         
          //Check if Password 1 equals to Password 2. 
        }else if (!pass1.equals(pass2)) {
            
            JOptionPane.showMessageDialog(rootPane, "Password Doesn't Match!","ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }else{
        return true;
        }
    }
    
    //Check If Username exists in Our Data Base.
    public boolean CheckUsername(String username){
        //Declare PreparedStatement and ResultSet variables.
            PreparedStatement pst;
            ResultSet res;
        // Initialize boolean variable to track if the username exists.    
            boolean Username_exist = false;
        // SQL query to check if the username already exists in the 'applicants' table     
        String Usernamequery = "SELECT * FROM `applicants` WHERE Username = ?";
        
        try {
            // Establish a database connection using a custom DBConnection class
            Connection dbcon = DBConnection.DBConnection();
            // Prepare the SQL statement with the username parameter
            pst = (PreparedStatement) dbcon.prepareStatement(Usernamequery);
            pst.setString(1, username);
            
            res = pst.executeQuery();
            // Check if the result set has any rows (username exists)
            if (res.next()) {
                Username_exist = true;
                JOptionPane.showMessageDialog(null,"This Username is Already Taken","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
        return Username_exist;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackLogin;
    private javax.swing.JButton Register;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtnumber;
    private javax.swing.JPasswordField txtpass1;
    private javax.swing.JPasswordField txtpass2;
    private javax.swing.JTextField txtusern;
    // End of variables declaration//GEN-END:variables


}

